export default {
  searchForm: document.getElementById('search-form'),
  searchError: document.getElementById('search-error'),
  watchedTab: document.getElementById('watched-tab'),
  queueTab: document.getElementById('queue-tab'),
  homeGallery: document.getElementById('home-gallery'),
  goTopBtn: document.getElementById('back-to-top'),
  youTubeVideo: document.querySelector('div[data-action="video"]'),
  openRegistrationBtn: document.querySelector('[data-registration-open]'),
  libraryGallery: document.getElementById('library-gallery'),
  registerForm: document.getElementById('register_form'),
  openModalBtn: document.querySelector('[data-footer-modal-open]'),
  closeModalBtn: document.querySelector('[data-footer-modal-close]'),
  footerModal: document.querySelector('[data-modal]'),
  pagination: document.querySelector('[data-el="pagination"]'),
  // searchInput: document.getElementById('search-input'),
  // searchResults: document.getElementById('search-results'),
};
